# Generated by Django 4.2.6 on 2023-11-17 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cadastro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='comentario_fotos/'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(default='default_profile.jpg', upload_to='profile_pics/')),
                ('nome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.autor')),
            ],
        ),
    ]
