# Generated by Django 4.2.6 on 2023-11-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_comentario_foto_perfil_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='comments_pics/'),
        ),
    ]
