# Generated by Django 4.2.6 on 2023-11-18 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_noticia_imagem_alter_comentario_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['-data'], 'verbose_name': 'Autores', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='conteudo',
            new_name='texto',
        ),
        migrations.AddField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(choices=[('Entrevista', 'Entrevista'), ('Filme', 'Filme'), ('Música', 'Música')], max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
