# Generated by Django 4.2.6 on 2023-11-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customuser_delete_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='nome',
            new_name='username',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
