# Generated by Django 4.2.6 on 2023-11-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_noticia_autor_noticia_user_delete_autor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
        migrations.RenameField(
            model_name='categorias',
            old_name='categoria',
            new_name='categorias',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
