# Generated by Django 4.2.6 on 2023-12-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_cadastro_managers_remove_cadastro_senha_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
