# Generated by Django 4.2.6 on 2023-12-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_delete_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='categorias',
        ),
        migrations.AddField(
            model_name='categorias',
            name='categoria',
            field=models.CharField(choices=[('Entrevista', 'Entrevista'), ('Filme', 'Filme'), ('Música', 'Música')], default='', max_length=100),
        ),
    ]
