# Generated by Django 4.2.6 on 2023-12-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_categorias_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
    ]
